HarborMaster - MVC w dummy repo/HarborMasterFromEmployeeMgmtCA/Models/Craft.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HarborMasterFromEmployeeMgmtCA.Models
{
    public class Craft
        
    {
        public int OwnerID { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public int DockNumber { get; set; }
        public string NameOfCraft { get; set; }
        public int LOA { get; set; }
        public int CraftTypeID { get; set; }
        public int MembershipID { get; set; }

    }
}

HarborMaster - MVC w dummy repo/HarborMasterFromEmployeeMgmtCA/Models/CraftType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HarborMasterFromEmployeeMgmtCA.Models
{
    public class CraftType
    {
        public int CraftTypeID { get; set; }
        public string TypeOfCraft { get; set; }

    }
}

HarborMaster - MVC w dummy repo/HarborMasterFromEmployeeMgmtCA/Controllers/CraftsController.cs
using HarborMasterFromEmployeeMgmtCA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HarborMasterFromEmployeeMgmtCA.Controllers
{
    public class CraftsController : Controller
    {
        [HttpGet]
        public ActionResult List()
        {
            List<CraftListViewModel> model = (from craft in CraftRepo.GetAll()
                                              join craftType in CraftTypeRepo.GetAll() on craft.CraftTypeID equals craftType.CraftTypeID
                                              join membership in MembershipRepo.GetAll() on craft.MembershipID equals membership.MembershipID
                                              select new CraftListViewModel()
                                              {
                                                  Owner = craft.OwnerFirstName + " " + craft.OwnerLastName,
                                                  MembershipType = membership.MembershipType,
                                                  DockNumber = craft.DockNumber,
                                                  NameOfCraft = craft.NameOfCraft,
                                                  TypeOfCraft = craftType.TypeOfCraft,
                                                  LOA = craft.LOA,
                                                  OwnerID = craft.OwnerID,

                                              }).ToList();
                
            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            AddCraftViewModel model = new AddCraftViewModel();

            model.CraftTypes = GetCraftTypeSelectList();

            model.MembershipTypes = GetMembershipSelectList();

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(AddCraftViewModel model)
        {
            Craft craft = new Craft();

            if(ModelState.IsValid)
            {
                craft.OwnerFirstName = model.OwnerFirstName;
                craft.OwnerLastName = model.OwnerLastName;
                craft.NameOfCraft = model.NameOfCraft;
                craft.DockNumber = model.DockNumber;
                craft.LOA = model.LOA;
                craft.MembershipID = model.MembershipID;
                craft.CraftTypeID = model.CrafTypeID;

                CraftRepo.Add(craft);

                return RedirectToAction("List");
            }
            else
            {
                model.CraftTypes = GetCraftTypeSelectList();

                model.MembershipTypes = GetMembershipSelectList();

                return View(model);
            }
            
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var craft = CraftRepo.GetCraft(id);

            var model = new EditCraftViewModel();
            model.OwnerFirstName = craft.OwnerFirstName;
            model.OwnerLastName = craft.OwnerLastName;
            model.OwnerID = craft.OwnerID;
            model.DockNumber = craft.DockNumber;
            model.LOA = craft.LOA;
            model.NameOfCraft = craft.NameOfCraft;
            model.MembershipID = craft.MembershipID;
            model.CrafTypeID = craft.CraftTypeID;

            model.MembershipTypes = GetMembershipSelectList();
            model.CraftTypes = GetCraftTypeSelectList();

            return View(model);

        }

        [HttpPost]
        public ActionResult Edit(EditCraftViewModel model)
        {
            Craft craft = new Craft();

            if (ModelState.IsValid)
            {
                craft.OwnerID = model.OwnerID;
                craft.OwnerFirstName = model.OwnerFirstName;
                craft.OwnerLastName = model.OwnerLastName;
                craft.NameOfCraft = model.NameOfCraft;
                craft.DockNumber = model.DockNumber;
                craft.LOA = model.LOA;
                craft.MembershipID = model.MembershipID;
                craft.CraftTypeID = model.CrafTypeID;

                CraftRepo.Edit(craft);

                return RedirectToAction("List");
            }
            else
            {
                model.CraftTypes = GetCraftTypeSelectList();

                model.MembershipTypes = GetMembershipSelectList();

                return View(model);
            }
        }

        private List<SelectListItem> GetCraftTypeSelectList()
        {
            return (from craftType in CraftTypeRepo.GetAll()
                    select new SelectListItem()
                    {
                        Text = craftType.TypeOfCraft,
                        Value = craftType.CraftTypeID.ToString(),
                    }).ToList();
        }

        private List<SelectListItem> GetMembershipSelectList()
        {
            return (from membership in MembershipRepo.GetAll()
                    select new SelectListItem()
                    {
                        Text = membership.MembershipType,
                        Value = membership.MembershipID.ToString(),
                    }).ToList();
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            CraftRepo.Delete(id);
            return RedirectToAction("List");
                
        }
    }

}

HarborMaster - MVC w dummy repo/HarborMasterFromEmployeeMgmtCA/Views/Crafts/Add.cshtml
@model HarborMasterFromEmployeeMgmtCA.Models.AddCraftViewModel
@{
    ViewBag.Title = "Add";
}

<h2>Add a Craft</h2>
@Html.ValidationSummary()
@using (Html.BeginForm("Add", "Crafts", FormMethod.Post))
{
    <div class="form-group">
        <label>Owner: First Name</label>
        @Html.TextBoxFor(c => c.OwnerFirstName, new { @class = "form-control"})
    </div>
    <div class="form-group">
        <label>Owner: Last Name</label>
        @Html.TextBoxFor(c => c.OwnerLastName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Membership Type</label>
        @Html.DropDownListFor(c => c.MembershipID, Model.MembershipTypes, "-SELECT-", new { @class = "form-control"})
    </div>
    <div class="form-group">
        <label>Craft Name</label>
        @Html.TextBoxFor(c => c.NameOfCraft, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Length</label>
        @Html.TextBoxFor(c => c.LOA, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Craft Type</label>
        @Html.DropDownListFor(c => c.CrafTypeID, Model.CraftTypes, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Dock Assignment</label>
        @Html.TextBoxFor(c => c.DockNumber, new { @class = "form-control" })
    </div>

    @Html.ActionLink("Cancel", "List", "Crafts", null, new { @class = "btn btn-default" })
    <button class="btn btn-primary">Save</button>
}

HarborMaster - MVC w dummy repo/HarborMasterFromEmployeeMgmtCA/Views/Crafts/Edit.cshtml
@model HarborMasterFromEmployeeMgmtCA.Models.EditCraftViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Crafts", FormMethod.Post))
{
    @Html.ValidationSummary()

    @Html.HiddenFor(c => c.OwnerID)
    <div class="form-group">
        <label>Owner: First Name</label>
        @Html.TextBoxFor(c => c.OwnerFirstName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Owner: Last Name</label>
        @Html.TextBoxFor(c => c.OwnerLastName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Membership Type</label>
        @Html.DropDownListFor(c => c.MembershipID, Model.MembershipTypes, "-SELECT-", new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Craft Name</label>
        @Html.TextBoxFor(c => c.NameOfCraft, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Length</label>
        @Html.TextBoxFor(c => c.LOA, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Craft Type</label>
        @Html.DropDownListFor(c => c.CrafTypeID, Model.CraftTypes, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Dock Assignment</label>
        @Html.TextBoxFor(c => c.DockNumber, new { @class = "form-control" })
    </div>

    @Html.ActionLink("Cancel", "List", "Crafts", null, new { @class = "btn btn-default" })
    <button class="btn btn-primary">Save</button>
}

HarborMaster - MVC w dummy repo/HarborMasterFromEmployeeMgmtCA/Views/Crafts/List.cshtml
@model List<HarborMasterFromEmployeeMgmtCA.Models.CraftListViewModel>
@{
    ViewBag.Title = "ListOfCraft";
}

<h2><strong>List of Craft in the MIYC Harbor</strong></h2>
<h4>@Html.ActionLink("Add a New Craft", "Add", "Crafts")</h4>
<div class="row">
    <div class="col-xs-10">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Owner</th>
                    <th>Membership</th>
                    <th>Dock Number</th>
                    <th>Craft Name</th>
                    <th>Type</th>
                    <th>Length</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var craft in Model)
                {
                    <tr>
                        <td>@craft.Owner</td>
                        <td>@craft.MembershipType</td>
                        <td>@craft.DockNumber</td>
                        <td>@craft.NameOfCraft</td>
                        <td>@craft.TypeOfCraft</td>
                        <td>@craft.LOA</td>
                        <td>
                            @Html.ActionLink("EDIT", "Edit", "Crafts", new { id = craft.OwnerID }, null)
                        </td>
                        <td>
                            @using (Html.BeginForm("Delete", "Crafts", new { id = craft.OwnerID }, FormMethod.Post))
                            {
                                <button class="btn btn-danger" onclick="return confirm('Are you sure you want to remove @craft.Owner from the registry?');">REMOVE</button>
                            }

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>